services:
  mysql:
    image: mysql:8.4
    container_name: ems_mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ems_db
      MYSQL_USER: ems_user
      MYSQL_PASSWORD: ems123
      MYSQL_ROOT_PASSWORD: 123
      TZ: Asia/Jakarta
    ports:
      - "3307:3306"
    volumes:
      - ems_mysql_data:/var/lib/mysql

volumes:
  ems_mysql_data: